<?php

if (!function_exists('icms_getModuleConfig')) {
	die('Error: This file can\'t be accesed directly!');
}

$module_config = &icms_getModuleConfig('build-dvd');

$runfile = array(
				'mkisofs' => $module_config['build_dvd_path'].'/mkisofs',
				'httrack' => $module_config['build_dvd_path2'].'/httrack'
				);

$path = ICMS_CACHE_PATH.'/build-iso';

if (!file_exists($path)) {
	if (!icms_mkdir($path)) {
		die('ERROR: Can\'t create cache path!');
	}
}

$script_path = ICMS_CACHE_PATH.'/build-iso-s';

if (!file_exists($script_path)) {
	if (!icms_mkdir($script_path)) {
		die('ERROR: Can\'t create script file!');
	}
}

$commands = array(sprintf('"%s" "%s" -O "%s" --search-index -q',$runfile['httrack'], XOOPS_URL, $path),
				  sprintf('"%s" -no-bak -J -udf -o %s %s', $runfile['mkisofs'], ICMS_CACHE_PATH.'/site.iso', ICMS_CACHE_PATH.'/build-iso'));

$is_win = stristr(PHP_OS, 'WIN');

chdir($script_path);
if ($is_win) {
   $filename = "script.bat";
   $fp = fopen($filename, 'w');
   fwrite($fp, "@ECHO OFF\r\n\r\n");
   fwrite($fp, "REM #################################################\r\n");
   fwrite($fp, "REM This scripts was generated by build-dvd from iCMS\r\n");
   fwrite($fp, "REM #################################################\r\n\r\n");
   fwrite($fp, "del /f /s /q \"" . str_replace('/',"\\", ICMS_CACHE_PATH) . '\\site.iso' . "\" \r\n");
   fwrite($fp, "del /f /s /q \"$path\\*\" \r\n\r\n");
   fwrite($fp, "echo [autorun] > $path\\autorun.inf" . "\r\n");
   fwrite($fp, "echo open=Chrome\\chrome.exe --user-data-dir=Profil --incognito index.html >> \"$path\\autorun.inf\"" . "\r\n");
   fwrite($fp, "echo icon=Chrome\\chrome.exe,0 >> \"$path\\autorun.inf\"" . "\r\n");
   fwrite($fp, "echo label=Site Offline Version >> \"$path\\autorun.inf\"" . "\r\n\r\n");
   fwrite($fp, "xcopy \"" . str_replace("/","\\",$module_config['build_dvd_path3']) . "\\\"* \"$path\\\"* /E /C /H /Y \r\n\r\n");
} else {
   $filename = "script.sh";
   $fp = fopen($filename, 'w');
   fwrite($fp, "#!/bin/sh\r\n\r\n");
   fwrite($fp, "# #################################################\r\n");
   fwrite($fp, "# This scripts was generated by build-dvd from iCMS\r\n");
   fwrite($fp, "# #################################################\r\n\r\n");
   fwrite($fp, "rm -rf \"" . ICMS_CACHE_PATH . '/site.iso' . "\" \r\n");
   fwrite($fp, "rm -rf \"$path\\*\" \r\n\r\n");
   fwrite($fp, "echo \\[autorun\\] > $path/autorun.inf" . "\r\n");
   fwrite($fp, "echo open=Chrome\\\\chrome.exe --user-data-dir=Profil --incognito index.html >> $path/autorun.inf" . "\r\n");
   fwrite($fp, "echo icon=Chrome\\\\chrome.exe,0 >> $path/autorun.inf" . "\r\n");
   fwrite($fp, "echo label=Site Offline Version >> $path/autorun.inf" . "\r\n\r\n");
   fwrite($fp, "cp -R " . $module_config['build_dvd_path3'] . "/* $path/* \r\n\r\n");
}
foreach ($commands as $command) {
   fwrite($fp, $command . "\r\n\r\n");
}
fclose($fp);

if (!$is_win) {
	@chmod($filename, 777);
}

if ($is_win) {
	system("%comspec% /C \"$filename\"");
} else {
	system("$filename");
}

?>